### ISSUE TITLE
DRBDAdapter cannot correctly identify the system version

### ISSUE THREAD

**Issue by san3Xian** [hwameistor/hwameistor-operator#290]
hwameistor operator version: v0.14.4  
https://github.com/hwameistor/hwameistor-operator/blob/8d06d4a0cfdabe11d57ae212d0387927d2d7d569/pkg/install/drbd/drbd_adapter.go#L117-L131  
https://github.com/hwameistor/hwameistor-operator/blob/8d06d4a0cfdabe11d57ae212d0387927d2d7d569/pkg/install/drbd/drbd_adapter.go#L43-L51  
<img width="1457" alt="image" src="https://github.com/user-attachments/assets/dd3c3dcc-408c-4405-825f-f6bde13751d8">  

The regular expression uses **wildcards too broadly**, causing issues with version identification.  
<img width="1500" alt="image" src="https://github.com/user-attachments/assets/3f31696e-d48a-431a-bb62-eb674dffb446">  

BTW, Why did hwameistor **delete all the DRBD installation jobs**? This causes significant difficulties for troubleshooting and identification.

**Comment by SSmallMonster** [comment]
>Why did hwameistor delete all the DRBD installation jobs? This causes significant difficulties for troubleshooting and identification.

You are right. From my opinion, jobs that are stopped with failure should be reserved until user delete them manually for other purposes e.g. reinstall. Is there any logs shown that jobs were deleted by hwameistor-operator and how to reproduce it. 

cc @peng9808

**Comment by san3Xian** [comment]
Moreover, I cannot simply re-trigger the DRBD driver installation by editing the cluster resource, and the failed jobs was disapper😭

**Comment by SSmallMonster** [comment]
As the error for incorrectly indentify OS version, maybe we should use more strict regex to distinguish `Major`, `Minor` version from /etc/os-release.

**Comment by SSmallMonster** [comment]
> Moreover, I cannot simply re-trigger the DRBD driver installation by editing the cluster resource, and the failed jobs was disapper😭此外，我不能简单地通过编辑集群资源来重新触发 DRBD 驱动程序安装，并且失败的作业是 disapper😭

This has been one of our planned improvement.

**Comment by peng9808** [comment]
I will try to fix it in August

**Comment by peng9808** [comment]
The latest version of hwameistor-operator already supports re-triggering drbd installation by deleting failed jobs.

**Comment by peng9808** [comment]
https://github.com/hwameistor/hwameistor-operator/pull/306
